image: codogo/pipelines-universal:latest

pipelines:
  branches:
    master:
      - step:
          script:
          - yarn install 
          - yarn run lint
          - yarn run build
          - aws s3 sync --delete build s3://codogo-app-write-prod
